name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: deploy
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WASP_VERSION: 0.24.0
      RAILWAY_PROJECT_NAME: code-screenshot
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - run: npm install --global @wasp.sh/wasp-cli@$WASP_VERSION @railway/cli
      - run: wasp deploy railway deploy $RAILWAY_PROJECT_NAME --existing-project-id $RAILWAY_PROJECT_ID
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
