name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: deploy
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - run: npm install --global @wasp.sh/wasp-cli@0.24.0
      - run: wasp install
      - run: npm run build
      - run: test -f ./.wasp/out/web-app/build/200.html
      - run: test -f ./.wasp/out/web-app/build/index.html

      - run: npx --yes @infomiho/buzz-cli@0.7.0 deploy ./.wasp/out/web-app/build --subdomain code-screenshot --server https://static.miho.dev
        env:
          BUZZ_TOKEN: ${{ secrets.BUZZ_TOKEN }}
